apiVersion: v1
kind: Service
metadata:
  name: demo-krueger-api-svc
spec:
  type: NodePort
  selector:
    app: demo-krueger-api-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-krueger-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-krueger-api-pod
  template:
    metadata:
      labels:
        app: demo-krueger-api-pod
    spec:
      containers:
        - name: demo-krueger
          image: andersonkrueger/krueger:demo-krueger-1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: datasource_url
              value: jdbc:mariadb://10.111.80.84:3306/demo_krueger
