apiVersion: v1
kind: Service
metadata:
  name: demo-krueger-api-svc
spec:
  type: NodePort
  selector:
    app: demo-krueger-api-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
