apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-krueger-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-krueger-api-pod
  template:
    metadata:
      labels:
        app: demo-krueger-api-pod
    spec:
      containers:
        - name: demo-krueger
          image: andersonkrueger/kruegerpub:demo-krueger-1.1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: datasource_url
              value: jdbc:mariadb://10.111.80.84:3306/demo_krueger
